"""Configuration module."""

from .settings import (
    APP_TITLE, APP_ICON, APP_VERSION, APP_SUBTITLE,
    WOM_API_BASE, WOM_USER_AGENT,
    CACHE_TTL_PLAYER, CACHE_TTL_SNAPSHOTS, CACHE_TTL_ACHIEVEMENTS,
    SKILLS, SKILL_CATEGORIES, BOSS_CATEGORIES,
    ARCHETYPE_CONFIG, COLORS,
)

__all__ = [
    "APP_TITLE", "APP_ICON", "APP_VERSION", "APP_SUBTITLE",
    "WOM_API_BASE", "WOM_USER_AGENT",
    "CACHE_TTL_PLAYER", "CACHE_TTL_SNAPSHOTS", "CACHE_TTL_ACHIEVEMENTS",
    "SKILLS", "SKILL_CATEGORIES", "BOSS_CATEGORIES",
    "ARCHETYPE_CONFIG", "COLORS",
]
